query subspace($spaceID: UUID!, $subspaceNameID: NameID!) {
  lookup {
    space(ID: $spaceID) {
      subspaceByNameID(NAMEID: $subspaceNameID) {
        nameID
        id
        about {
          id
          profile {
            displayName
          }
        }
        community {
          id
          roleSet {
            id
          }
        }
        collaboration {
          id
          calloutsSet {
            id
            callouts {
              nameID
            }
          }
        }
      }
    }
  }
}
